version: 2.1

orbs:
  win: circleci/windows@2.4.1
  config-splitting: circle-makotom-orbs/config-splitting@0.0.1

setup: true

parameters:
  base-revision:
    type: string
    default: "main"

jobs:
  build-shared:
    executor:
      name: win/default
    working_directory: C:\Users\circleci\project\HelloWorld
    steps:
      - checkout:
          path: C:\Users\circleci\project
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "circleci-demo-windows.csproj" }}
            - dotnet-packages-v1-
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\project\HelloWorld\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "circleci-demo-windows.csproj" }}
      - run:
          name: "Run Build step"
          command: dotnet.exe publish -c Release -r win10-x64
      - run:
          name: "Test the executable"
          command: .\bin\Release\netcoreapp2.1\win10-x64\publish\circleci-demo-windows.exe 
      - store_artifacts:
          path: .\bin\Release\netcoreapp2.1\win10-x64\publish\circleci-demo-windows.exe


workflows:
  main-workflow:
    jobs:
      - build-shared # this job will always run
      - config-splitting/run-modular-configs-selectively:
          module-list-file: .circleci/list-of-dirs-to-monitor.txt
          base-revision: main
          requires:
            - build-shared
