version: 2.1

orbs:
  win: circleci/windows@2.4.1

parameters:
  webbrowser:
    type: boolean
    default: false
  notepadtest:
    type: boolean
    default: false


jobs:
  browser-tests:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: Run browser tests
          command: |
              cd WebBrowserTestsSample/tests/WebBrowserTests
              dotnet test

  ui-tests:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: choco install winappdriver
      - run: 
          name: Run winappdriver in background
          background: true
          command: | 
              cd "C:\Program Files (x86)\Windows Application Driver\"
              Start-Process -FilePath "WinAppDriver.exe" -Wait
      - run:
          name: Restore and build
          command: |
            cd NotepadTest
            nuget restore
            cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\msbuild\current\bin\"
            .\msbuild.exe "C:\Users\circleci\project\NotepadTest\NotepadTest.csproj"
      - run: 
          name: Run UI tests
          command: |
              cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\common7\ide\extensions\TestPlatform"
              .\vstest.console.exe C:\Users\circleci\project\NotepadTest\bin\debug\NotepadTest.dll

workflows:
  browser-tests:
    when: << pipeline.parameters.webbrowser >>
    jobs:
      - browser-tests

  ui-tests:
    when: << pipeline.parameters.notepadtest >>
    jobs:
      - ui-tests